#!/usr/bin/env bash
# Check out sync/upstream with the snapshot at $LATEST and print `base=main` or
# `base=sync`. A branch that holds $LATEST or carries rule, build or adapter
# commits main lacks is kept, so rule fixes for a held sync survive a new
# upstream SHA. Any other branch is reset to main.
set -euo pipefail

branch_sha=$(git show origin/sync/upstream:upstream/UPSTREAM.json 2>/dev/null | jq -r .sha || true)
fixes=$(git rev-list --count origin/main..origin/sync/upstream -- rules src adapters 2>/dev/null || echo 0)

if [ "$branch_sha" = "$LATEST" ] || [ "$fixes" -gt 0 ]; then
  git checkout -B sync/upstream origin/sync/upstream
  if ! git merge --no-edit origin/main; then
    # dist/ is regenerated by the build, so the branch's copy wins any conflict.
    git rm -rq --cached -- dist
    rm -rf dist
    git checkout HEAD -- dist
    git commit --no-edit
  fi
  if [ "$branch_sha" != "$LATEST" ]; then
    bun run fetch-upstream "$LATEST"
  fi
  echo "base=sync"
else
  git checkout -B sync/upstream origin/main
  bun run fetch-upstream "$LATEST"
  echo "base=main"
fi
